# Generated by Django 4.0.6 on 2023-02-28 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('category_name', models.CharField(max_length=255, verbose_name='商品类目名称')),
            ],
            options={
                'verbose_name': '团长招商活类目列表',
                'verbose_name_plural': '团长招商活类目列表',
                'db_table': 'Category',
            },
        ),
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('activity_id', models.CharField(max_length=255, verbose_name='活动ID')),
                ('item_title', models.CharField(max_length=255, verbose_name='商品标题')),
                ('item_id', models.CharField(max_length=255, primary_key=True, serialize=False, verbose_name='商品id')),
                ('item_img_url', models.CharField(max_length=255, verbose_name='商品图片链接')),
                ('item_stock', models.CharField(max_length=255, verbose_name='商品库存')),
                ('item_price', models.CharField(max_length=255, verbose_name='商品价格')),
                ('item_category_name', models.CharField(max_length=255, verbose_name='商品类目名称')),
                ('item_volume', models.CharField(max_length=255, verbose_name='商品销量')),
                ('web_url_type', models.CharField(choices=[('1', '小店'), ('2', '快分销')], default='', max_length=1, verbose_name='1=小店；2=快分销')),
                ('item_commission_rate', models.CharField(max_length=255, verbose_name='商品佣金率')),
                ('item_apply_time', models.CharField(max_length=255, verbose_name='商品报名时间')),
                ('investment_promotion_rate', models.CharField(max_length=255, verbose_name='团长服务费率')),
            ],
            options={
                'verbose_name': '团长招商活动已报名商品列表',
                'verbose_name_plural': '团长招商活动已报名商品列表',
                'db_table': 'Goods',
            },
        ),
    ]
