# Generated by Django 4.0.6 on 2023-03-04 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_address_citycode_address_cityname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='addressTag',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
