# Generated by Django 4.0.6 on 2023-03-15 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(0, '已完成'), (1, '待审批')], default=1),
        ),
    ]
